# Database connection properties
spring:
  profiles:
    active: "h2"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # /api-docs endpoint custom path
    api-docs:
      path: /api-docs
# Server port
server:
  port: 8081
  servlet:
    context-path: /gil-api