# Database connection properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gil-db
    username: postgres
    password: postgres

  # Other properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
